### PR TITLE
fix(content-type): change content type detection to take hint

### LINKED ISSUE #33: Wrong Content-Type for SVG assets
When uploading SVG Assets via API, content-type is inconsistent with UI Assets.

API Assets return `content-type: application/xml`
UI Assets return `content-type: image/svg+xml`

This becomes important e.g. when linking to SVG assets from Flex plugins as the current API asset Content-Type triggers CORB and such assets fail to load with error:

> Cross-Origin Read Blocking (CORB) blocked cross-origin response <url>.svg with MIME type text/plain. See https://www.chromestatus.com/feature/5629709824032768 for more details.

Can we have API assets return `content-type: image/svg+xml` just like UI assets do?

Example SVG to try this with: https://tangerine-toad-5117.twil.io/assets/feathercorp-logo-pumpkin.svg

### PR DESCRIPTION
**Pull request by dkundel**
For assets previously we would determine the content type from the buffer while ignoring the file
naming. This commit changes that by taking the name into consideration and only using buffer reading
as a fallback.

BREAKING CHANGE: Assets might be uploaded with a different content type going forward

fix #33

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

File: src/utils/content-type.ts [hunk 1]
```diff
@@ -10,14 +19,14 @@ import mime from 'mime-types';
  * @param {(string | Buffer)} content the content to check
  * @returns {(string | undefined)} a valid content type or undefined
```
Comment (philnash) [inline src/utils/content-type.ts:20]: The TypeScript types now say that this returns a `Promise<string | undefined>`, should update the docs/comments to reflect that.
